import '../../models/module_model.dart';
import '../../models/word_model.dart';

final ModuleModel modul4 = ModuleModel(
  id: 4,
  code: "modul4",
  title: 'Alışveriş',
  subtitle: 'Market • fiyat • ürünler',
  estimatedMinutes: 55,
  sections: const [
    ModuleSection(type: ModuleSectionType.intro, title: "Giriş", description: '', xpReward: 5),
    ModuleSection(type: ModuleSectionType.vocab, title: "Wortschatz", description: '', xpReward: 25),
    ModuleSection(type: ModuleSectionType.sentence, title: "Satzbau", description: '', xpReward: 20),
    ModuleSection(type: ModuleSectionType.listen, title: "Hören", description: '', xpReward: 20),
    ModuleSection(type: ModuleSectionType.speak, title: "Sprechen", description: '', xpReward: 25),
    ModuleSection(type: ModuleSectionType.exam, title: "Mini Prüfung", description: '', xpReward: 35),
  ],
  words: const [
    // eski 15
    WordItem(de: "das Brot", tr: "ekmek", trPron: "das brot", group: "Market"),
    WordItem(de: "die Milch", tr: "süt", trPron: "di milih", group: "Market"),
    WordItem(de: "das Wasser", tr: "su", trPron: "das vasa", group: "Market"),
    WordItem(de: "der Käse", tr: "peynir", trPron: "dea keze", group: "Market"),
    WordItem(de: "der Preis", tr: "fiyat", trPron: "dea prays", group: "Market"),
    WordItem(de: "billig", tr: "ucuz", trPron: "bilih", group: "Sıfat"),
    WordItem(de: "teuer", tr: "pahalı", trPron: "toya", group: "Sıfat"),
    WordItem(de: "die Kasse", tr: "kasa", trPron: "di kase", group: "Market"),
    WordItem(de: "die Karte", tr: "kart", trPron: "di karte", group: "Ödeme"),
    WordItem(de: "bar", tr: "nakit", trPron: "bar", group: "Ödeme"),
    WordItem(de: "Ich möchte ...", tr: "… istiyorum", trPron: "ih möh-te", group: "Kalıp"),
    WordItem(de: "Wie viel kostet das?", tr: "Bu ne kadar?", trPron: "vi fil kostet das", group: "Soru"),
    WordItem(de: "Haben Sie ...?", tr: "… var mı?", trPron: "haben zi", group: "Soru"),
    WordItem(de: "Wo finde ich ...?", tr: "… nerede bulurum?", trPron: "vo findı ih", group: "Soru"),
    WordItem(de: "Mit Karte, bitte.", tr: "Kartla lütfen.", trPron: "mit karte bite", group: "Ödeme"),

    // +30 yeni (3x hedef)
    WordItem(de: "die Tomate", tr: "domates", trPron: "di tomatə", group: "Market"),
    WordItem(de: "die Kartoffel", tr: "patates", trPron: "di karto-fel", group: "Market"),
    WordItem(de: "der Apfel", tr: "elma", trPron: "dea apfel", group: "Market"),
    WordItem(de: "die Banane", tr: "muz", trPron: "di banane", group: "Market"),
    WordItem(de: "das Fleisch", tr: "et", trPron: "das flayş", group: "Market"),
    WordItem(de: "das Gemüse", tr: "sebze", trPron: "das gemüze", group: "Market"),
    WordItem(de: "das Obst", tr: "meyve", trPron: "das opst", group: "Market"),
    WordItem(de: "die Butter", tr: "tereyağı", trPron: "di buta", group: "Market"),
    WordItem(de: "die Eier", tr: "yumurta", trPron: "di aya", group: "Market"),
    WordItem(de: "der Zucker", tr: "şeker", trPron: "dea tsuka", group: "Market"),
    WordItem(de: "das Salz", tr: "tuz", trPron: "das zalts", group: "Market"),
    WordItem(de: "die Tüte", tr: "poşet", trPron: "di tüte", group: "Market"),
    WordItem(de: "die Quittung", tr: "fiş", trPron: "di kvi-tung", group: "Market"),
    WordItem(de: "der Supermarkt", tr: "süpermarket", trPron: "dea zupa-markt", group: "Yer"),
    WordItem(de: "der Einkauf", tr: "alışveriş", trPron: "dea ayn-kauf", group: "İsim"),
    WordItem(de: "die Rechnung", tr: "hesap/fatura", trPron: "di rehnung", group: "Ödeme"),
    WordItem(de: "das Angebot", tr: "indirimli ürün", trPron: "das angəbot", group: "Market"),
    WordItem(de: "die Dose", tr: "konserve kutusu", trPron: "di doze", group: "Market"),
    WordItem(de: "die Flasche", tr: "şişe", trPron: "di flaşe", group: "Market"),
    WordItem(de: "das Stück", tr: "parça/adet", trPron: "das ştük", group: "Market"),
    WordItem(de: "ein Kilo", tr: "bir kilo", trPron: "ayn kilo", group: "Ölçü"),
    WordItem(de: "ein Liter", tr: "bir litre", trPron: "ayn lita", group: "Ölçü"),
    WordItem(de: "frisch", tr: "taze", trPron: "friş", group: "Sıfat"),
    WordItem(de: "alt", tr: "eski/bayat", trPron: "alt", group: "Sıfat"),
    WordItem(de: "süß", tr: "tatlı", trPron: "züüs", group: "Sıfat"),
    WordItem(de: "sauer", tr: "ekşi", trPron: "zaua", group: "Sıfat"),
    WordItem(de: "Ich nehme ...", tr: "… alıyorum", trPron: "ih neyme", group: "Kalıp"),
    WordItem(de: "Sonst noch etwas?", tr: "Başka bir şey?", trPron: "zonst noh etvas", group: "Kalıp"),
    WordItem(de: "Das ist alles.", tr: "Hepsi bu.", trPron: "das ist alles", group: "Kalıp"),
    WordItem(de: "Danke, tschüss.", tr: "Teşekkürler, hoşça kal.", trPron: "danke çüs", group: "Kalıp"),
  ],
);