name: almanca_ogreniyorum
description: Almanca Akademi Uygulaması
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # internet api
  http: ^1.2.1

  # dosya sistemi
  path_provider: ^2.1.3

  # audio oynatma (Cloud TTS için)
  just_audio: ^0.9.46

  # hashing (cache vs)
  crypto: ^3.0.3

  # local storage
  shared_preferences: ^2.2.3

  # speech recognition (mikrofon)
  speech_to_text: ^7.0.0

  # text to speech
  flutter_tts: ^3.8.5

  # state management (ileride gerekli olacak)
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/ui/
    - assets/data/words_basic_a1.json
    - assets/data/sentences_a1.json
    - assets/data/sprechen/