import '../../models/module_model.dart';
import '../../models/word_model.dart';

final ModuleModel modul5 = ModuleModel(
  id: 5,
  code: "modul5",
  title: 'Yol ve Yardım',
  subtitle: 'Yön sorma • ulaşım • yardım',
  estimatedMinutes: 60,
  sections: const [
    ModuleSection(type: ModuleSectionType.intro, title: "Giriş", description: '', xpReward: 5),
    ModuleSection(type: ModuleSectionType.vocab, title: "Wortschatz", description: '', xpReward: 25),
    ModuleSection(type: ModuleSectionType.sentence, title: "Satzbau", description: '', xpReward: 20),
    ModuleSection(type: ModuleSectionType.listen, title: "Hören", description: '', xpReward: 20),
    ModuleSection(type: ModuleSectionType.speak, title: "Sprechen", description: '', xpReward: 25),
    ModuleSection(type: ModuleSectionType.exam, title: "Mini Prüfung", description: '', xpReward: 35),
  ],
  words: const [
    WordItem(de: "der Bahnhof", tr: "tren istasyonu", trPron: "dea baan-hof", group: "Yer"),
    WordItem(de: "die Haltestelle", tr: "durak", trPron: "di haltə-ştelle", group: "Yer"),
    WordItem(de: "die Straße", tr: "sokak/cadde", trPron: "di ştraase", group: "Yer"),
    WordItem(de: "links", tr: "sol", trPron: "links", group: "Yön"),
    WordItem(de: "rechts", tr: "sağ", trPron: "rehts", group: "Yön"),
    WordItem(de: "geradeaus", tr: "dümdüz", trPron: "geraade-aus", group: "Yön"),
    WordItem(de: "Entschuldigung", tr: "afedersiniz", trPron: "ent-şuldigung", group: "Kalıp"),
    WordItem(de: "Können Sie mir helfen?", tr: "Bana yardım edebilir misiniz?", trPron: "können zi mia helfen", group: "Kalıp"),
    WordItem(de: "Ich verstehe nicht.", tr: "Anlamıyorum.", trPron: "ih fea-şteye niht", group: "Kalıp"),
    WordItem(de: "Bitte langsam.", tr: "Lütfen yavaş.", trPron: "bite langzam", group: "Kalıp"),
    WordItem(de: "Bitte wiederholen.", tr: "Lütfen tekrar edin.", trPron: "bite vida-holın", group: "Kalıp"),
    WordItem(de: "Wie spät ist es?", tr: "Saat kaç?", trPron: "vi şpeet ist es", group: "Soru"),
    WordItem(de: "Wo ist ...?", tr: "… nerede?", trPron: "vo ist", group: "Soru"),
    WordItem(de: "Ich brauche ...", tr: "… ihtiyacım var", trPron: "ih brauhe", group: "Kalıp"),
    WordItem(de: "das Ticket", tr: "bilet", trPron: "das tiket", group: "Ulaşım"),
    WordItem(de: "der Eingang", tr: "giriş", trPron: "dea ayn-gang", group: "Yer"),
    WordItem(de: "der Ausgang", tr: "çıkış", trPron: "dea aus-gang", group: "Yer"),
    WordItem(de: "die Polizei", tr: "polis", trPron: "di politsay", group: "Yardım"),
    WordItem(de: "das Krankenhaus", tr: "hastane", trPron: "das kranken-haus", group: "Yer"),
    WordItem(de: "die Apotheke", tr: "eczane", trPron: "di apote-ke", group: "Yer"),
    WordItem(de: "hier", tr: "burada", trPron: "hia", group: "Yer"),
    WordItem(de: "dort", tr: "orada", trPron: "dort", group: "Yer"),
    WordItem(de: "nahe", tr: "yakın", trPron: "naahe", group: "Sıfat"),
    WordItem(de: "weit", tr: "uzak", trPron: "vayt", group: "Sıfat"),
    WordItem(de: "die Nummer", tr: "numara", trPron: "di numa", group: "İsim"),
    WordItem(de: "die Adresse", tr: "adres", trPron: "di adresə", group: "İsim"),
    WordItem(de: "Ich habe keine Zeit.", tr: "Zamanım yok.", trPron: "ih habe kaynə tsayt", group: "Kalıp"),
    WordItem(de: "Ich bin verloren.", tr: "Kayboldum.", trPron: "ih bin fea-loren", group: "Kalıp"),
    WordItem(de: "Können Sie das aufschreiben?", tr: "Bunu yazabilir misiniz?", trPron: "können zi das auf-şrayben", group: "Kalıp"),
    WordItem(de: "Danke!", tr: "Teşekkürler!", trPron: "danke", group: "Kalıp"),
  ],
);